# Generated by Django 2.1.3 on 2019-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
