# Generated by Django 2.0.6 on 2018-07-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='user_requests',
        ),
    ]
