# Generated by Django 2.0.6 on 2018-07-06 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20180706_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_approved',
            field=models.ManyToManyField(related_name='approved_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='user_requests',
            field=models.ManyToManyField(related_name='requested_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
