# Generated by Django 2.0.6 on 2018-07-26 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180706_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='user_approved',
            field=models.ManyToManyField(blank=True, related_name='approved_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='user_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
